name: ci
on: [push, pull_request]
jobs:
  build-and-deploy:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Test 🔧
        run: |
          npm install
          npm run lint

      - name: Build 🙅‍♀️
        run: |
          npm run build

      - name: Deploy 🚀
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: mengsixing/mengsixing.github.io
          BRANCH: master
          FOLDER: docs/.vuepress/dist
          CLEAN: true
